on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: NtFreX-Function-HelloWorld
  DOTNET_VERSION: '3.1.100'
  NODE_VERSION: ''

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout git'
      uses: actions/checkout@master
      
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Setup Node.js ${{ env.NODE_VERSION }}'
      uses: 'actions/setup-node@v1'
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Setup .NET Core ${{ env.DOTNET_VERSION }}'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Run dotnet build'
      shell: bash
      run: |
        pushd .
        dotnet build src/server/Azure.Functions.HelloWorld.csproj --configuration Release --output ./server_output
        popd

    - name: 'Run npm install and ng build'
      run: |
        npm install
        ng build --prod
        ng test
        
    - name: 'Deploy Azure Functions'
      uses: azure/functions-action@v1.1.2
      id: fa
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: './server_output'
  
    - name: 'Deploy static html'
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.AZURE_FTP_PATH }}
        FTP_USERNAME: ${{ secrets.AZURE_FTP_USER }}
        FTP_PASSWORD: ${{ secrets.AZURE_FTP_PWD }}
        ARGS: --delete
        LOCAL_DIR: 'src/client/dist/client'
        REMOTE_DIR: 'site/wwwroot'
