on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: NtFreX-Function-HelloWorld
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '2.1'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use .NetCore ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: build
      run: |
        dotnet build Azure.Functions.HelloWorld.csproj
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
