on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: NtFreX-Function-HelloWorld
  DOTNET_VERSION: '2.1.607'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout git'
      uses: actions/checkout@master
    
    - name: 'Setup .NET Core ${{ env.DOTNET_VERSION }}'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Run dotnet build'
      shell: bash
      run: |
        pushd .
        dotnet build --configuration Release --output ./output
        popd
        
    - name: 'Deploy Azure Functions'
      uses: azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
